server:
  port: 8080
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true     # Show the queries which are executed.
  sql:
    init:
      mode: always  # always execute schema.sql
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*" # Will allow us to refresh properties in runtime
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true # enables actuator/info
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "Bank loans application"
    version: "1.0.0"

logging:
  level:
    com:
      cnsn:
        loans: DEBUG